---

- name: check added hosts
  debug:
    msg: "Added hosts"

- name: copy deployment to temp variable
  set_fact:
     tmp_deployment: "{{ deployment }}"
  when: deployment is defined

- name: set default deployment
  vars:
    types:
      kolla:
      contrail:
  set_fact:
    deployment: "{{ deployment|default({})|combine({'type': types }) }}"
  when: deployment is undefined or deployment.type is undefined

- name: install packages for kolla ansible deployer
  include: contrail-kolla-ansible/main.yml
  when: deployment.type.kolla is defined

- name: install packages for contrail ansible deployer
  include: contrail-ansible-deployer/main.yml
  when: deployment.type.contrail is defined
