- name: Provision OpenStack cluster with kolla
  command: >
    ansible-playbook -i inventory/all-in-one all.yml -v
  become: true
  become_user: root
  environment:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_STDOUT_CALLBACK: debug
  args:
    chdir: /contrail-kolla-ansible/ansible

- name: Provision with Contrail
  command: >
    ansible-playbook -i inventory/ playbooks/deploy.yml -v
  become: true
  become_user: root
  environment:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_STDOUT_CALLBACK: debug
  args:
    chdir: /contrail-ansible-deployer