#- name: Update all packages to the latest version
#  apt:
#    upgrade: dist

- name: install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - git

#- name: Disable UFW
#  ufw:
#    state: enabled

