SKU, Contrail-Version, OS, Deployment-Type(kolla/helm/ooo) etal

- name: Read SKU
  command: echo "{{ lookup('env','SKU') }}"
  register: sku

- name: Read OS type
  command: echo "{{ lookup('env','OS') }}"
  register: os

- name: Read contrail version
  command: echo "{{ lookup('env','CONTRAIL_VERSION') }}"
  register: contrail_version

- name: Read contrail version
  command: echo "{{ lookup('env','DEPLOYMENT_TYPE') }}"
  register: deployment_type

- name: create temp directory
  tempfile:
     state: directory
     suffix: _test
  register: tmpdir

- name: Pull docker test image
  docker_image:
    name: "{{ deployment.type.test_registry }/contrail-test-test:{{ contrail_version }}-{{ os }}-{{ sku}}"
    state: present

- name: Get testrunner script from github
  get_url:
    url: "https://raw.githubusercontent.com/Juniper/contrail-test-ci/master/testrunner.sh"
    dest: "{{ tmpdir.path }}/testrunner.sh"
    mode: 0755

- name: Generate testbed.yml file
  template:
    src: testbed.yml.j2
    dest: "{{ tmpdir.path }}/testbed.yml"

- name: List contrail-test containers
  command: >
    ./testrunner.sh list -i
  args:
    chdir: "{{ tmpdir.path }}"
  register: container_list

- debug:
    msg: "Container exists"
  when: '"{{ contrail_version }}-{{ os }}-{{ sku }}" in container_list.stdout'

- name: Run contrail-test containers
  command: >
    ./testrunner.sh run -t testbed.py -s "opencontrailnightly/contrail-test-test:{{ contrail_version }}-{{ os }}-{{ sku }}"
  args:
    chdir: "{{ tmpdir.path }}"

