
deployment:
    type:
        kolla:
            branch: contrail/ocata
            registry: docker.io
        contrail:
            branch: master
            registry: ci-repo.englab.juniper.net
    sku: ocata
    os: centos74
    version: master-20180202171825
    orchestrator: openstack

provider_config:
  bms:
    ssh_pwd: c0ntrail123
    ssh_user: root
    ntpserver: 10.84.5.100
    domainsuffix: local

instances:
  bms1:
    provider: bms
    ip: 10.0.0.4
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:

  bms2:
    provider: bms
    ip: 10.0.0.5
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:

  bms3:
    provider: bms
    ip: 10.0.0.6
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:

  bms4:
    provider: bms
    ip: 10.0.0.7
    roles:
      vrouter:

  bms5:
    provider: bms
    ip: 10.0.0.10
    roles:
      vrouter:

contrail_configuration:
  AAA_MODE: rbac
  CONFIG_API_USE_SSL:
  INTROSPECT_SSL_ENABLE:
  XMPP_SSL_ENABLE:
  METADATA_PROXY_SECRET:
  CONTROLLER_NODES: 10.10.0.4,10.10.0.5,10.10.0.6

orchestrator_configuration:
    keystone:
        version:
        username:
        password: c0ntrail123
        project:
        region_name:
        ssl:
            certs:
    internal_vip: 10.10.0.200
    external_vip: 10.0.0.200
    network_interface: eth1

test_configuration:
    image_web_server:
    mail_server:
    report_path:
    log_path:
    keystonev3_use_project_scope:
