deployment:
    type:
        kolla:
            branch: contrail/ocata
            registry: docker.io/kolla
        contrail:
            branch: master
            registry: docker.io/opencontrailnightly
    sku: ocata
    os: centos74
    version: master-20180131150536
    orchestrator: openstack

network:
    ntpserver: 10.84.5.100

container_hosts:
    hosts:
        10.84.7.199:
            ansible_user: root
            ansible_ssh_pass: c0ntrail123

interfaces:
    10.84.7.199:
        control:
            mac_address :
            ip-address :

roles:
    10.84.7.199:
        configdb:
        config:
        control:
        webui:
        analytics:
        analyticsdb:
        vrouter:
        tsn:
        esxi:
        tor-agent:
        k8smaster:
        openstack:

contrail_configs:
    config_aaa_mode: rbac
    analytics_aaa_mode:
    internal_vip:
    external_vip:

orchestrator_configs:
    keystone:
        version:
        username:
        password: c0ntrail123
        project:
        ssl:
            certs:
            region_name:
    internal_vip: 10.84.7.199
    external_vip:

test_configs:
    image_web_server:
    mail_server:
    report_path:
    log_path:
    keystonev3_use_project_scope:
