deployment:
    type:
        kolla:
            branch: contrail/ocata
            registry: ci-repo.englab.juniper.net:5000
        contrail:
            branch: master
            registry: ci-repo.englab.juniper.net:5000
    sku: ocata
    os: centos7
    version: master-centos7-ocata-bld-8
    orchestrator: openstack

provider_config:
  bms:
    ssh_pwd: c0ntrail123
    ssh_user: root
    ntpserver: 10.84.5.100

instances:
  bms1:
    provider: bms
    ip: 10.0.0.4
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:

  bms2:
    provider: bms
    ip: 10.0.0.5
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:

  bms3:
    provider: bms
    ip: 10.0.0.6
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:

  bms4:
    provider: bms
    ip: 10.0.0.7
    roles:
      vrouter:

  bms5:
    provider: bms
    ip: 10.0.0.10
    roles:
      vrouter:

contrail_configuration:
  AAA_MODE: no-auth
  CONTROLLER_NODES: 10.0.0.4,10.0.0.5,10.0.0.6
  VROUTER_GATEWAY: 10.0.0.1
  PHYSICAL_INTERFACE: eth0

orchestrator_configuration:
    keystone:
        version: v3
        username:
        password: c0ntrail123
        project:
        region_name:
    internal_vip: 10.0.0.200
    network_interface: eth0

test_configuration:
    image_web_server: 10.84.5.120
    use_project_scoped_token: True
    public_host: 10.84.5.120
    web_server:
        server:
        username:
        password:
        report_path:
        log_path:
        web_root:
    mail_server:
        server:
        port:
        to:
        sender:
