
deployment:
    type:
        kolla:
            branch: contrail/ocata
            registry: docker.io
        contrail:
            branch: master
            registry: docker.io/opencontrailnightly
    sku: ocata
    os: centos74
    version: master-20180131150536

network:
    ntpserver: 10.84.5.100

container_hosts:
    hosts:
        10.0.0.4:
            ansible_user: root
            ansible_ssh_pass: c0ntrail123
            network_interface: eth1
            kolla_external_vip_interface: eth0
        10.0.0.5:
            ansible_user: root
            ansible_ssh_pass: c0ntrail123
            network_interface: eth1
            kolla_external_vip_interface: eth0
        10.0.0.6:
            ansible_user: root
            ansible_ssh_pass: c0ntrail123
            network_interface: eth1
            kolla_external_vip_interface: eth0
        10.0.0.7:
            ansible_user: root
            ansible_ssh_pass: c0ntrail123
            network_interface: eth1
            kolla_external_vip_interface: eth0
        10.0.0.10:
            ansible_user: root
            ansible_ssh_pass: c0ntrail123
            network_interface: eth1
            kolla_external_vip_interface: eth0

roles:
    10.0.0.5:
        config_database:
        config:
        control:
        webui:
        analytics:
        analytics_database:
        openstack:

    10.0.0.6:
        config_database:
        config:
        control:
        webui:
        analytics:
        analytics_database:
        openstack:

    10.0.0.10:
        config_database:
        config:
        control:
        webui:
        analytics:
        analytics_database:
        openstack:

    10.0.0.4:
        vrouter:

    10.0.0.7:
        vrouter:

contrail_configs:
    AAA_MODE: rbac
    METADATA_PROXY_SECRET: c0ntrail123
    CONFIG_NODES: 10.10.0.3,10.10.0.5,10.10.0.10
    ANALYTICS_NODES: 10.10.0.3,10.10.0.5,10.10.0.10
    PHYSICAL_INTERFACE: eth1
    VROUTER_GATEWAY: 10.10.0.1 

orchestrator_configs:
    keystone:
        version:
        username:
        password: c0ntrail123
        project:
        region_name:
        ssl:
            certs:
    internal_vip: 10.10.0.200
    external_vip: 10.0.0.200
    network_interface: eth1

test_configs:
    image_web_server:
    mail_server:
    report_path:
    log_path:
    keystonev3_use_project_scope:
