
deployment_type: kolla_contrail

container_hosts:
   hosts:
        10.87.118.138:
            ansible_user: root
            ansible_ssh_pass: c0ntrail123

network:
    ntpserver: 10.84.5.100

interfaces:
    10.84.7.207:
        control:
            mac_address :
            ip-address :

roles:
    10.84.7.207:
        configdb:
        config:
        control:
        webui:
        analytics:
        analyticsdb:
        vrouter:
        tsn:
        k8smaster:
        esxi:
        tor-agent:

contrail_configs:
    config_aaa_mode:
    analytics_aaa_mode:
    internal_vip:
    external_vip:

orchestrator_configs:
    keystone:
        version:
        username:
        password: c0ntrail123
        project:
        ssl:
            certs:
            region_name:
    internal_vip: 10.84.118.138
    external_vip:

test_configs:
    image_web_server:
    mail_server:
    report_path:
    log_path:
    keystonev3_use_project_scope: