
deployment_type: kolla_contrail

container_hosts:
   hosts:
        10.84.7.199:
            ansible_user: root
            ansible_ssh_pass: c0ntrail123

network:
    ntpserver: 10.84.5.100

interfaces:
    10.84.7.199:
        control:
            mac_address :
            ip-address :

contrail_configs:
  roles:
    10.84.7.199:
        configdb:
        config:
        control:
        webui:
        analytics:
        analyticsdb:
        vrouter:
        tsn:
        k8smaster:
        esxi:
        tor-agent:

  config_aaa_mode: yes
  analytics_aaa_mode:
  internal_vip:
  external_vip:

roles:
    10.84.7.199:
        configdb:
        config:
        control:
        webui:
        analytics:
        analyticsdb:
        vrouter:
        tsn:
        k8smaster:
        esxi:
        tor-agent:

orchestrator_configs:
    keystone:
        version:
        username:
        password: c0ntrail123
        project:
        ssl:
            certs:
            region_name:
    internal_vip: 10.84.7.199
    external_vip:

test_configs:
    image_web_server:
    mail_server:
    report_path:
    log_path:
    keystonev3_use_project_scope: