deployment:
    type:
        kolla:
            branch: contrail/ocata
            registry: docker.io
        contrail:
            branch: master
            registry: docker.io/opencontrailnightly
    sku: ocata
    os: centos74
    version: master-20180131150536

network:
    ntpserver: 10.84.5.100

container_hosts:
    hosts:
        10.84.7.199:
            ansible_user: root
            ansible_ssh_pass: c0ntrail123
            network_interface: eth0
            kolla_external_vip_interface: eth0
        10.87.118.138:
            ansible_user: root
            ansible_ssh_pass: c0ntrail123
            network_interface: eth0
            kolla_external_vip_interface: eth0

roles:
    10.84.7.199:
        vrouter:
    10.87.118.138:
        configdb:
        config:
        control:
        webui:
        analytics:
        analyticsdb:
        tsn:
        esxi:
        tor-agent:
        k8smaster:
        openstack:

contrail_configs:
    AAA_MODE: rbac

orchestrator_configs:
    keystone:
        version:
        username:
        password: c0ntrail123
        project:
        ssl:
            certs:
            region_name:

test_configs:
    image_web_server:
    mail_server:
    report_path:
    log_path:
    keystonev3_use_project_scope:
